### ISSUE TITLE
The source code doesn't build

### ISSUE THREAD

**Issue by AlexGS74** [PacktPublishing/Hands-On-Data-Structures-and-Algorithms-with-Rust#1]
It seem the workspace is miss-configured (folders and projects do not match Capter01/Ch1). Also the build instructions do not mention that you should use nightly to make it build.

![image](https://user-images.githubusercontent.com/8890708/52026264-d0694900-24cc-11e9-9ac8-57998e79d264.png)

As most of us are new to Rust this is a major road block.

**Comment by AlexGS74** [comment]
To build this you'll need to rename folders from 'Chapter01' to 'Ch1' etc.

Then you need to install nightly with `rustup install nightly`.

Once it's done, in the project\workspace root directory use command `rustup override add nightly` to switch the project to use nightly.

Use `cargo build` to build it. There will be many warnings, but no errors with 1.34 nightly.

**Comment by celaus** [comment]
Thank you for solving this yourself, I'll update the workspace Cargo.toml to match the new chaper names
