### ISSUE TITLE
Chapter 4, page 56: LIFO should be FIFO ?

### ISSUE THREAD

**Issue by modulitos** [PacktPublishing/Hands-On-Data-Structures-and-Algorithms-with-Rust#2]
Perhaps I'm missing something, but on chapter 4, page 56, it describes a list as LIFO, but I think it means FIFO.

It describes a Linked List where we want to append something to the list, then read the list from beginning to end, which sounds like FIFO to me:

>...it's a queue (or LIFO - short for Last In First Out) structure.

AFAIK, queues are typically FIFO, and stacks are LIFO.

![book-error](https://user-images.githubusercontent.com/4207017/57602665-a33d2580-7514-11e9-9d2c-837792439938.png)

**Comment by celaus** [comment]
Hi! yes you are right - I meant FIFO. Unfortunately this mistake hasn't been corrected in the books 😓

**Comment by deepesh-packt** [comment]
Hey @celaus and @modulitos ,

I've marked this correction in the Errata section of the README.md file of this repo.

Thanks for highlighting.
