### ISSUE TITLE
Lists, Lists, And More Lists - Further reading

### ISSUE THREAD

**Issue by srufle** [PacktPublishing/Hands-On-Data-Structures-and-Algorithms-with-Rust#3]
I was reading **Hands-On Data Structures and Algorithms with Rust** on oreilly.com
https://learning.oreilly.com/library/view/hands-on-data-structures/9781788995528/d86cb77c-5314-442c-a98c-3e7a8f5032e7.xhtml

In the Further reading section of Chapter4 - "Lists, Lists, And More Lists"
I think the "Skip Lists: Done Right"  link is a duplicate of the "Implementing the Iterator trait"

- Implementing the Iterator trait (https://doc.rust-lang.org/std/iter/index.html#implementing-iterator)
- Skip Lists: Done Right (https://doc.rust-lang.org/std/iter/index.html#implementing-iterator)

I google and maybe it was supposed to be 
https://15721.courses.cs.cmu.edu/spring2018/papers/08-oltpindexes1/skiplists-done-right2016.pdf

**Comment by celaus** [comment]
Right, thanks for noticing - you are right it' the wrong link.

**Comment by JosephA-packt** [comment]
I hope your query has been answered @srufle . Hence I would be closing this issue.
